### PR TITLE
Fix Pull Request

### PR DESCRIPTION
**Pull request by JohanesPeterV**
In this pull request, I've adjusted env for deployment and adjusted for migration without migrate:fresh

### CODE REVIEW

**Comment by Admin-growmodo** [comment]
Hi @JohanesPeterV,
You had removed the package.json file.
Can you update the file "`.github/workflows/main.yml`" on your branch with this value: (from [`main` branch](https://github.com/Growmodo-GmbH/laravel-test/blob/main/.github/workflows/main.yml))

image

Thank you!

**Comment by Admin-growmodo** [comment]
@JohanesPeterV Please note that our automated deployment does not `migrate:fresh`, so you should not modify all existing migration files. Thanks!

**Review by Admin-growmodo — CHANGES_REQUESTED** [review]
Please apply the changes. Thank you!

**Comment by JohanesPeterV** [comment]
> @JohanesPeterV Please note that our automated deployment does not `migrate:fresh`, so you should not modify all existing migrations. Thanks!

So should i revert my migration to the first migration since i created a pull request ? 
Thanks in advance

**Review by JohanesPeterV — COMMENTED** [review]
ok

**Pull request closed without merging**
