### PR TITLE
rojspagsanjan-laravel-test

### PR DESCRIPTION
**Pull request by rojspagsanjan**

### CODE REVIEW

**Comment by Admin-growmodo** [comment]
Thank you! @rojspagsanjan

**Comment by Admin-growmodo** [comment]
@rojspagsanjan Your app has been deployed at [https://test.growmodo.dev/rojspagsanjan/public](https://test.growmodo.dev/rojspagsanjan/public)

**Comment by rojspagsanjan** [comment]
Hi Maam/Sir,

Is my Laravel test working and can ready to test? Please let me know. Thank
you

Sincerely,
Rojs Pagsanjan

**Comment by Admin-growmodo** [comment]
Hi @rojspagsanjan,
You can check it here: [https://test.growmodo.dev/rojspagsanjan/public](https://test.growmodo.dev/rojspagsanjan/public)
On our end, it does not load the contents of the page. Can you submit a PR with the fixes that are needed or instructions? Thanks!

Our automated deployment performs the following steps:
> npm install
> npm run build
> composer install --no-interaction --prefer-dist --optimize-autoloader
> php artisan migrate --force
> php artisan optimize:clear

Does your app need extra commands to run? Please let us know.
You can also create a shell file `commands.sh` on the main folder, then add the shell script commands to perform.

**Pull request merged**
