### PR TITLE
Fixed APP_URL

### PR DESCRIPTION
**Pull request by marlontamo**

### CODE REVIEW

**Comment by Admin-growmodo** [comment]
This is not needed. The deployed assets are automatically updated with the correct values. You can check here [deploy-marlontamo-laravel-test .env](https://github.com/Growmodo-GmbH/laravel-test/blob/deploy-marlontamo-laravel-test/.env)

Your app has been deployed at https://test.growmodo.com/marlontamo-laravel-test/public/

**Comment by marlontamo** [comment]
I can see the deployed app sir?

**Comment by Admin-growmodo** [comment]
> 
You can check it here: https://test.growmodo.com/marlontamo-laravel-test/public/

I tried creating an account and it has an error. Please check the attached screenshot. Thanks!
image

**Comment by marlontamo** [comment]
the app is connected to the database

**Comment by marlontamo** [comment]
I tried the app on my hosting and it is working fine
here is the url:

https://robinsonslandcorporation.site/laravel-test/public/

**Comment by Admin-growmodo** [comment]
@marlontamo, you previously submitted a [PR to the main branch](https://github.com/Growmodo-GmbH/laravel-test/pull/34), but YOU MUST ONLY submit a PR to the branch assigned to you which is [marlontamo-laravel-test](https://github.com/Growmodo-GmbH/laravel-test/tree/marlontamo-laravel-test).
I have manually made the changes from that PR with this commit reference: [Landing fix from @marlontamo:landing ](https://github.com/Growmodo-GmbH/laravel-test/commit/b1abde07edc8f839229ac0f76511e57512481447)

> https://robinsonslandcorporation.site/laravel-test/public/ 

Please check the [link](https://robinsonslandcorporation.site/laravel-test/public/ ) you provided, and our automated deployed [URL](https://test.growmodo.com/marlontamo-laravel-test/public/). They have the same signup error as shown in the screenshot provided above.

image

>image

**Comment by marlontamo** [comment]
the app are having those errors because of the credentials in connecting
the database are in correct
 i have uploaded it in hostinger and the app is working
here is my URL: ->https://robinsonslandcorporation.site/laravel-test/public/

**Comment by Admin-growmodo** [comment]
> the app are having those errors because of the credentials in connecting the database are in correct i have uploaded it in hostinger and the app is working here is my URL: ->https://robinsonslandcorporation.site/laravel-test/public/
> […](#)

NOPE! It is not a DB Credential error. Please read the error message on the screenshot or try it yourself. You mentioned you app is working in hostinger url you provided but it is not, I just tested it and gave you a screenshot above.

**Pull request closed without merging**
