### PR TITLE
Rogenpagsanjan laravel test

### PR DESCRIPTION
**Pull request by rojspagsanjan**

### CODE REVIEW

**Comment by Admin-growmodo** [comment]
Hello @rojspagsanjan!
The branch name assigned to you is ["rojspagsanjan"](https://github.com/Growmodo-GmbH/laravel-test/tree/rojspagsanjan) or https://github.com/Growmodo-GmbH/laravel-test/tree/rojspagsanjan
Please use and submit a PR only on this branch. Thank you!

Notes:
- Follow [README.md](https://github.com/Growmodo-GmbH/laravel-test/tree/rojspagsanjan)
- The branch [rojspagsanjan](https://github.com/Growmodo-GmbH/laravel-test/tree/rojspagsanjan)  is ahead from main with an automated commit: "[Peronalize new branch](https://github.com/Growmodo-GmbH/laravel-test/commit/94f4637c46cb8870ead67dbf610856e69359ea54)"

Important Changes:
```
DB_DATABASE='rojspagsanjan'
```

**Comment by rojspagsanjan** [comment]
Hi Maam/Sir,

I have this error on pushing my changes, I think there is a restriction on
the admin that I am not allowed to push my changes. Can I ask for
assistance? Thank you

[image: image.png]

**Comment by rojspagsanjan** [comment]
Here is the screenshot: https://drive.google.com/drive/folders/1pUH2U_o2TTK86PgT5ghx5NGmtCAnViux?usp=sharing

**Comment by Admin-growmodo** [comment]
Hello @rojspagsanjan,
Yes, you can't push changes directly to this repository because you don't have permission.
All you need to do is follow the instructions mentioned in [README.md](https://github.com/Growmodo-GmbH/laravel-test) from [Setup](https://github.com/Growmodo-GmbH/laravel-test#setup) to submitting a [Pull Request (PR)](https://github.com/Growmodo-GmbH/laravel-test#push-and-pull-request-pr)

What you did here by submitting this PR is correct, but there are some missing steps, like starting to work and submitting a PR only to the branch assigned to you.

**Pull request closed without merging**
